# Generated by Django 4.1 on 2022-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='no_foto.png', null=True, upload_to='product_images', verbose_name='Картинка'),
        ),
    ]
